name: Build, Test and Release
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - name: Run test
        run: npm run test
      - name: Build lib files
        run: npm run build
      - name: Release package
        run: npm publish --access public
        env:
          NPM_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
        if: contains(github.ref, 'tags/v')
