name: Build, Test and Release
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn install
      - name: Run test
        run: yarn test
      - name: Build lib files
        run: yarn build
      - name: Release package
        run: yarn publish --access public
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        if: contains(github.ref, 'tags/v')
