name: Build, Test and Release
on:
  push:
    tags:
      - '**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - name: Run test
        run: npm run test
      - name: Build lib files
        run: npm run build
      - name: Setup release
        if: contains(github.ref, 'tags/v')
        run: echo //registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN} > .npmrc
        env:
          NPM_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
      - name: Release package
        if: contains(github.ref, 'tags/v')
        run: npm publish --access public
